# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-20 15:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created', models.DateTimeField()),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='ship.Ship')),
            ],
        ),
    ]
