# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-20 16:10
from __future__ import unicode_literals

import csv
import datetime
from django.db import migrations
from django.contrib.gis.geos import Point


def fill_out_csv_data(apps, schema_editor):
    Ship = apps.get_model('ship', 'Ship')

    with open('data/positions.csv', 'r') as csvFile:
        reader = csv.reader(csvFile)
        for row in reader:
            ship = Ship.objects.get(imo_number=row[0])
            point = Point(x=float(row[3]), y=float(row[2]))
            date = datetime.datetime.strptime(row[1][:-3], '%Y-%m-%d %H:%M:%S')
            ship.positions.create(
                location=point,
                created=date
            )


def delete_positions(apps, schema_editor):
    Position = apps.get_model('location', 'Position')
    Position.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('ship', '0002_create_ships')
    ]

    operations = [
        migrations.RunPython(fill_out_csv_data, reverse_code=delete_positions)
    ]
